[Main]
Action=Dungeon
Player=1
VMName=LDPlayer
LDPath=C:\LDPlayer\LDPlayer9\ldconsole.exe
Language=English
StopBotAfter=0
CheckDifficult=No
AttackMethod=Precise
LootMethod=Stop
HealthPlayerAt=60
IHavePetWithBlacksmith=No
[Farm]
FarmMap=Cementery
Difficulty=H8
Bestiary=5
[Fish]
FishType=Gold
Fish_Iter=10
Maps=Bilefen
Difficult=I3
[LastRun]
mapName=cementery
step=step8
position=0
[SpotFarm]
SpotFarmMap=model_LibraryWest
SpotFarmDifficulty=I3
AcceptPartyInvites=No
CheckPartyLeader=Yes
CheckBestyaryEveryIfNotification=10
CheckBestyaryEveryIfNotificationNotFound=120
StopIfDetectMonster=Yes
text_count_yellow_dust2=0
text_count_scrap2=0
SpotFarmCustomModelMap=Library
[Telegram]
text=0
Active=No
Token=YOUR_TELEGRAM_TOKEN_HERE
text2=0
text3=0
text4=0
[Dungeon]
name=Kikuras
Difficult=H8
Team_solo=Solo
Time_to_exit=1000
Time_to_wait_party=400
text_count_dungeon=0
[Cyrangar]
Mode=Endless
StayAtTheDoor=Yes
Time_to_exit=50
get_fog_bane=No
[Fish2]
Fish2Type=Gold
Fish2_Iter=3
Maps=Bilefen
Difficult=H1
Zones=bridge1
text_count_yellow_dust=0
text_count_scrap=0
CHeckInventoryPercent=50
text_actual_iter=0
Fish2_IterMin=13
Fish2_IterMax=15
roundcicles=0
